/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.60 from the
 * contents of GLPsol.xs. Do not edit this file, edit GLPsol.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "lib/Algorithm/GLPK/GLPsol.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <glpk.h>

#include "glpsol.c"

/* _argv : is an ARRAY_REF of cli-params to glpsol executable.
	   For example ['-m', $programfile, '-o', $outputfile]
	   see https://en.wikibooks.org/wiki/GLPK/Using_GLPSOL
	   for glpsol's command-line parameters.
   VERBOSITY : optionally specify the verbosity level as an integer
	   of zero or more. Default is zero which is mute.
*/

/* note: varargs: https://www.lemoda.net/xs/xs-variable-arguments/index.html */

#line 29 "lib/Algorithm/GLPK/GLPsol.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%" UVxf ")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

/* simple backcompat versions of the TARGx() macros with no optimisation */
#ifndef TARGi
#  define TARGi(iv, do_taint) sv_setiv_mg(TARG, iv)
#  define TARGu(uv, do_taint) sv_setuv_mg(TARG, uv)
#  define TARGn(nv, do_taint) sv_setnv_mg(TARG, nv)
#endif

#line 180 "lib/Algorithm/GLPK/GLPsol.c"

XS_EUPXS(XS_Algorithm__GLPK__GLPsol_glpsol); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Algorithm__GLPK__GLPsol_glpsol)
{
    dVAR; dXSARGS;
    if (items < 1)
       croak_xs_usage(cv,  "_argv, ...");
    {
	SV *	_argv = ST(0)
;
#line 26 "lib/Algorithm/GLPK/GLPsol.xs"
	I32 argc = 0;
	char **argv = NULL;
	int VERBOSITY = 0;

#line 196 "lib/Algorithm/GLPK/GLPsol.c"
	int	RETVAL;
	dXSTARG;
#line 31 "lib/Algorithm/GLPK/GLPsol.xs"
	/* handle varargs: only VERBOSITY at the moment */
	if( items > 1 ){
		if( items > 2 ){ 
			fprintf(stderr, "glpsol() : error, the number of variable arguments after the 1st parameter (argv) must be zero or one (VERBOSITY).\n");
			RETVAL = 1;
			goto EXIT;
		}
		/* we have exactly one extra arg: VERBOSITY */
		VERBOSITY = (int )SvNV(ST(1)); /* the 2nd arg (first of varargs) */
	}

	SV* tmpSV = NULL;
	AV* inpArray = NULL;
	if( ! SvROK(_argv) ){
		fprintf(stderr, "glpsol() : error, input expected to be an ARRAY_REF/1.\n");
		RETVAL = 1;
		goto EXIT;
		//XSRETURN(1);
	}
	/* we know we have a reference */
	tmpSV = (SV* )SvRV(_argv); /* deref */
	if( SvTYPE(tmpSV) != SVt_PVAV) {
		fprintf(stderr, "glpsol() : error, input expected to be an ARRAY_REF/2.\n");
		RETVAL = 1;
		goto EXIT;
		//XSRETURN(1);
	}
	/* it's an array reference */
	inpArray = (AV* )tmpSV;

	argc = av_len(inpArray) + 1;
	if( VERBOSITY > 0 ){ fprintf(stdout, "starting with %d args ...\n", argc); }

	/* argv should contain the parameters to glpsol
	   but first item is the program name, so we need 1 extra item here:
	*/
	argv = (char **)malloc((argc+1)*sizeof(char *));
	for(int i=argc;i-->0;){
		SV *tmp = *av_fetch(inpArray,i,0);
		STRLEN len;
		char *str = SvPVutf8(tmp,len);
		argv[i+1] = strdup(str);
	}
	argv[0] = strdup("glpsol");
	if( VERBOSITY > 0 ){
	  for(int i=0;i<=argc;i++){
		fprintf(stdout, "glpsol() : parsed input (argv) param #%d as '%s'\n", i, argv[i]);
	  }
	}
	argc++;

	int ret = glpsol(argc, argv);
	if( ret != 0 ){
		fprintf(stderr, "error, call to glpsol() has failed.\n");
		RETVAL = 1;
	} else {
		RETVAL = 0;
	}

	if( VERBOSITY > 0 ){
		fprintf(stdout, "glpsol() : done and returning back to Perl.\n");
	}

	EXIT:

#line 265 "lib/Algorithm/GLPK/GLPsol.c"
	TARGi((IV)RETVAL, 1);
	ST(0) = TARG;
#line 100 "lib/Algorithm/GLPK/GLPsol.xs"
	if( argv != NULL ){
		if( VERBOSITY > 0 ){ fprintf(stdout, "glpsol() : cleaning up ...\n"); }
		for(int i=argc;i-->0;){
		  if( argv != NULL ){
			if( VERBOSITY > 0 ){ fprintf(stdout, "glpsol() : freeing memory for argv[%d] ...\n", i); }
			free(argv[i]);
		  }
		}
		if( VERBOSITY > 0 ){ fprintf(stdout, "glpsol() : freeing memory for argv.\n"); }
		free(argv);
	} else {
		if( VERBOSITY > 0 ){ fprintf(stdout, "glpsol() : nothing to clean up.\n"); }
	}
#line 282 "lib/Algorithm/GLPK/GLPsol.c"
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C" {
#endif
XS_EXTERNAL(boot_Algorithm__GLPK__GLPsol); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Algorithm__GLPK__GLPsol)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if PERL_VERSION_LE(5, 8, 999) /* PERL_VERSION_LT is 5.33+ */
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("Algorithm::GLPK::GLPsol::glpsol", XS_Algorithm__GLPK__GLPsol_glpsol);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

#ifdef __cplusplus
}
#endif
